#spring, db, thymeleaf
spring:
  profiles:
    active: local
  mvc:
    static-path-pattern: /static/**
  datasource:
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/DEMO?characterEncoding=UTF-8&serverTimezone=asia/seoul&useSSL=false
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

#server
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 8080
  error:
    whitelabel:
      enabled: true

#mybatis
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

#csp
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    s3:
      bucket:
    region:
      static: ap-northeast-2
    stack:
      auto: false


---
#dev


---
#sandbox


---
#cbt


---
#prod
