# DB 설정
spring:
  profiles:
    active: local
  datasource:
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/DEMO?characterEncoding=UTF-8&serverTimezone=asia/seoul&useSSL=false

# 서버 설정
server:
  port: 8080

#mybatis 설정
mybatis:
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

---
# DEV

---
# SANDBOX

---
# CBT

---
# PROD